describe('SwitchPages', () => {
    it('transition', () => {
        cy.visit('/')
        cy.intercept('https://mc.yandex.md/**', { log: false })
        cy.intercept('https://mc.yandex.ru/**', { log: false })
        cy.get('#menuActivator').click()
        cy.get('.v-overlay__content').contains('Аренда').click()
        cy.url().should('include', '/adverts/rent')
        cy.contains('поселок Российский').click()
        cy.get('.galery')
            .find('.v-window__controls')
            .find('.rl').click()
        // cy.get('[data-v-25230f8d]').click()
        // cy.get('[placeholder="Login"]').type('admin')
        // cy.get('[placeholder="Login"]').should('have.value', 'admin')
    })
})